In [1]:
import pandas as pd
import numpy as np

# Reliance ka data load karte hain pehle
df = pd.read_csv('../data/reliance_2024.csv')
df.head()

,Price,Close,High,Low,Open,Volume
0,Ticker,RELIANCE.NS,RELIANCE.NS,RELIANCE.NS,RELIANCE.NS,RELIANCE.NS
1,Date,NaN,NaN,NaN,NaN,NaN
2,2024-01-01,1279.69287109375,1287.8940202608817,1271.2447008145452,1274.9006856426909,4030540
3,2024-01-02,1290.2900390625,1291.920402508132,1271.1706293129728,1277.099135940161,7448800
4,2024-01-03,1276.25927734375,1301.3071935056118,1273.2455715878027,1289.450180352941,9037536

In [3]:
print(df.shape)
print(df.info())
print(df.isnull().sum())
df

(247, 6)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 247 entries, 0 to 246
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Price   247 non-null    object
 1   Close   246 non-null    object
 2   High    246 non-null    object
 3   Low     246 non-null    object
 4   Open    246 non-null    object
 5   Volume  246 non-null    object
dtypes: object(6)
memory usage: 11.7+ KB
None
Price     0
Close     1
High      1
Low       1
Open      1
Volume    1
dtype: int64

,Price,Close,High,Low,Open,Volume
0,Ticker,RELIANCE.NS,RELIANCE.NS,RELIANCE.NS,RELIANCE.NS,RELIANCE.NS
1,Date,NaN,NaN,NaN,NaN,NaN
2,2024-01-01,1279.69287109375,1287.8940202608817,1271.2447008145452,1274.9006856426909,4030540
3,2024-01-02,1290.2900390625,1291.920402508132,1271.1706293129728,1277.099135940161,7448800
4,2024-01-03,1276.25927734375,1301.3071935056118,1273.2455715878027,1289.450180352941,9037536
...,...,...,...,...,...,...
242,2024-12-23,1211.834716796875,1216.6926661807136,1202.8125341694108,1204.5971709809228,10052824
243,2024-12-24,1212.2808837890625,1222.988463211123,1210.545867189896,1211.8347850736238,6734917
244,2024-12-26,1206.1339111328125,1217.1883476811242,1203.8535553911518,1213.767935093776,10016178
245,2024-12-27,1210.595458984375,1217.3867853075249,1206.5800865394056,1207.86900439277,7000397
246,2024-12-30,1200.3338623046875,1212.7268365212021,1197.7561478726802,1205.9851311625014,8818766

In [4]:
df = pd.read_csv('../data/reliance_2024.csv', 
                 skiprows=[1, 2], index_col=0, parse_dates=True)
df.index.name = 'Date'
df.head()

                  Close         High          Low         Open   Volume
Date
2024-01-01  1279.692871  1287.894020  1271.244701  1274.900686  4030540
2024-01-02  1290.290039  1291.920403  1271.170629  1277.099136  7448800
2024-01-03  1276.259277  1301.307194  1273.245572  1289.450180  9037536
2024-01-04  1282.854736  1289.376190  1274.184391  1278.581319  9612778
2024-01-05  1288.313843  1294.316528  1283.521657  1285.942416  8086406

In [5]:
print(df.shape)
print(df.dtypes)
df.head()
df

(245, 5)
Close     float64
High      float64
Low       float64
Open      float64
Volume      int64
dtype: object

                  Close         High          Low         Open    Volume
Date
2024-01-01  1279.692871  1287.894020  1271.244701  1274.900686   4030540
2024-01-02  1290.290039  1291.920403  1271.170629  1277.099136   7448800
2024-01-03  1276.259277  1301.307194  1273.245572  1289.450180   9037536
2024-01-04  1282.854736  1289.376190  1274.184391  1278.581319   9612778
2024-01-05  1288.313843  1294.316528  1283.521657  1285.942416   8086406
...                 ...          ...          ...          ...       ...
2024-12-23  1211.834717  1216.692666  1202.812534  1204.597171  10052824
2024-12-24  1212.280884  1222.988463  1210.545867  1211.834785   6734917
2024-12-26  1206.133911  1217.188348  1203.853555  1213.767935  10016178
2024-12-27  1210.595459  1217.386785  1206.580087  1207.869004   7000397
2024-12-30  1200.333862  1212.726837  1197.756148  1205.985131   8818766

[245 rows x 5 columns]

In [6]:
stocks_names = ['reliance', 'tcs', 'infosys', 'hdfc_bank', 'wipro']
clean_data = {}

for name in stocks_names:
    df_temp = pd.read_csv(f'../data/{name}_2024.csv', skiprows=[1, 2], index_col=0, parse_dates=True)
    df_temp.index.name = 'Date'
    clean_data[name] = df_temp
    print(f"{name} cleaned — Shape: {df_temp.shape} ✅")

reliance cleaned — Shape: (245, 5) ✅
tcs cleaned — Shape: (245, 5) ✅
infosys cleaned — Shape: (245, 5) ✅
hdfc_bank cleaned — Shape: (245, 5) ✅
wipro cleaned — Shape: (245, 5) ✅

In [7]:
for name, df_temp in clean_data.items():
    missing = df_temp.isnull().sum().sum()
    print(f"{name}: {missing} missing values")

reliance: 0 missing values
tcs: 0 missing values
infosys: 0 missing values
hdfc_bank: 0 missing values
wipro: 0 missing values

In [8]:
import os
os.makedirs('../data/cleaned', exist_ok=True)

for name, df_temp in clean_data.items():
    df_temp.to_csv(f'../data/cleaned/{name}_clean.csv')

print("All cleaned data saved! ✅")

All cleaned data saved! ✅